### ISSUE TITLE
I don't see the option to generate the classes

### ISSUE THREAD

**Issue by joshdaquino** [Mighty16/JSONToKotlinClass#1]
Linux, Android studio 3.0.1, JSONToKotlinClass 1.5.1

I don't see the option to generate the classes when I rightclick on a package.

However, it available on Alt+K inside a file.

**Comment by Mighty16** [comment]
@joshdaquino, Hi! I think you are using another plugin for json. You can download my at https://plugins.jetbrains.com/plugin/10054-generate-kotlin-data-classes-from-json. The latest version is 0.8.4. And you say you are using JSONToKotlinClass 1.5.1. Maybe you missed github page))
